# Generated by Django 2.2.28 on 2026-01-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_delete_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='classes',
            name='max_students',
            field=models.IntegerField(default=25, verbose_name='Capacité maximum'),
        ),
        migrations.AddField(
            model_name='classes',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la formation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_months', models.IntegerField(default=6, verbose_name='Durée en mois')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('max_students_per_class', models.IntegerField(default=25, verbose_name='Capacité par classe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='formations', to='configuration.Subjects')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='configuration.Formation'),
        ),
    ]
