# Generated by Django 2.2.1 on 2025-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='type',
            field=models.IntegerField(choices=[(0, 'Absent'), (1, 'Present'), (2, 'Partial')], default=0),
        ),
    ]
